services:
  clickhouse:
    build:
      context: ./docker/clickhouse
      dockerfile: Dockerfile
    environment:
      CLICKHOUSE_PASSWORD: admin
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  api:
    build:
      context: ./docker/server
      dockerfile: Dockerfile
