[package]
name = "server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "api_analytic_metered_usage"
path = "main.rs"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
metered_usage = { path = "../../services/metered_usage" }
