name: Push container image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/afsoon/${{ steps.meta.outputs.REPO_NAME }}:latest
            ghcr.io/afsoon/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Build API image
        run: |
          docker build -f docker/server/Dockerfile -t ghcr.io/afsoon/metered_usage_rust:v0 --target prod .
          docker push ghcr.io/afsoon/store:latest
